scan_filter_chain:
- name: AngularBoundsFilter
  type: laser_filters/LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle: 1.57
    #3.14/180*50 = 0.872
    #3.14/180*90 = 1.57
    upper_angle: -1.57 
    #3.14/180*(-50) = -0.872
